Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using practiceWeb.Models.Dbcontext;
using practiceWeb.Models.UoW;
using Newtonsoft.Json;

namespace practiceWeb.Controllers
{
    public class LoginController : Controller
    {
        private readonly IUnitOfWork _unitOfwork; 
        public LoginController(IUnitOfWork unitOfWork)
        {
            _unitOfwork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }

        [Route("Login/Auth")]
        public async Task<JsonResult> LoginAction(string username, string password)
        {
            var x = await _unitOfwork._login.getLoginInfo(username, password);
            if (x.respcode == 1)
            {
                var identity = new ClaimsIdentity(new[]
                {
                    new Claim(ClaimTypes.Name, x._userdata.LastName),
                    new Claim(ClaimTypes.Email, username),
                    new Claim(ClaimTypes.Role, x._data.UserRole),
                    new Claim(ClaimTypes.Sid, "123")
                }, CookieAuthenticationDefaults.AuthenticationScheme
                 , ClaimTypes.Name, ClaimTypes.Role);



                var principal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync(
                    CookieAuthenticationDefaults.AuthenticationScheme,
                    principal);
            }
            return Json(x);
        }
        [Route("RegisterForm")]
        public IActionResult Register()
        {
            return View("~/Views/Login/RegisterForm.cshtml");
        }

        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction(nameof(Index));
        }
        [Route("RegisterUser")]
        public async Task<JsonResult> AddUserMethod(string data)
        {
            var loginInfo = (TbLogin)JsonConvert.DeserializeObject(data, typeof(TbLogin));
            var userInfo = (TbUserInfo)JsonConvert.DeserializeObject(data, typeof(TbUserInfo));
            loginInfo.UserRole = (string.IsNullOrEmpty(loginInfo.UserRole)) ? "User" : loginInfo.UserRole;
            userInfo.PermissionId = (loginInfo.UserRole == "Admin") ? 1 : 2;

            var x = await _unitOfwork._login.AddUser(loginInfo, userInfo);
            return Json(x);
        }
    }
}

Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace practiceWeb.Controllers
{
    [Authorize]
    public class MainController : Controller
    {
        [Route("MainPage")]
        //[Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            return View();
        }
        
        [Authorize(Roles = "User")]
        public IActionResult UserStartPage()
        {
            return View();
        }
    }
}

Views/Login/Index.cshtml
@{
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}

<div class="container">
    <div class="card card-login mx-auto mt-5">
        <div class="card-header">Login</div>
        <div class="card-body">

            <div class="form-group">
                <div class="form-label-group">
                    <input type="text" id="inputEmail" class="form-control" placeholder="Email address" required="required" autofocus="autofocus">
                    <label for="inputEmail">Email address</label>
                </div>
            </div>
            <div class="form-group">
                <div class="form-label-group">
                    <input type="password" id="inputPassword" class="form-control" placeholder="Password" required="required">
                    <label for="inputPassword">Password</label>
                </div>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input type="checkbox" value="remember-me">
                        Remember Password
                    </label>
                </div>
            </div>
            @*<a class="btn btn-primary btn-block" href="index.html">Login</a>*@
            <button type="button" class="btn btn-primary btn-block" id="submit_btn">Login</button>

            <div class="text-center">
                <a class="d-block small mt-3" href="@Url.Action("Register","Login")">Register an Account</a>
                <a class="d-block small" href="forgot-password.html">Forgot Password?</a>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script src="~/js/loginJs.js"></script>
}

Views/Login/RegisterForm.cshtml
@{
    ViewData["Title"] = "RegisterForm";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}

<div class="container">
    <div class="card card-register mx-auto mt-5">
        <div class="card-header">Register an Account</div>
        <div class="card-body">
            <form>
                <div class="form-group">
                    <div class="form-row">
                        <div class="col-md-4">
                            <div class="form-label-group">
                                <input type="text" id="firstName" class="form-control getDataCls" name="FirstName" placeholder="First name" required="required" autofocus="autofocus">
                                <label for="firstName">First name</label>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-label-group">
                                <input type="text" id="lastName" class="form-control getDataCls" name="LastName" placeholder="Last name" required="required">
                                <label for="lastName">Last name</label>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-label-group">
                                <input type="text" id="middleName" name="MiddleName" class="form-control getDataCls" placeholder="Middle name">
                                <label for="lastName">Middle name</label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <div class="form-row">
                            <div class="col-md-8">
                                <div class="form-label-group">
                                    <input type="email" id="inputEmail" class="form-control getDataCls" name="username" placeholder="Email address" required="required">
                                    <label for="inputEmail">Email address</label>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-label-group">
                                    <input type="text" id="userroles" class="form-control getDataCls" value="Admin" name="userRole" placeholder="User Role" readonly>
                                    <label for="inputEmail">User Role</label>
                                </div>
                            </div>
                        </div>
                    }
                    else
                    {
                        <div class="form-label-group">
                            <input type="email" id="inputEmail" class="form-control getDataCls" name="username" placeholder="Email address" required="required">
                            <label for="inputEmail">Email address</label>
                        </div>
                    }
                </div>
                <div class="form-group">
                    <div class="form-row">
                        <div class="col-md-6">
                            <div class="form-label-group">
                                <input type="password" id="inputPassword" name="password" class="form-control getDataCls" placeholder="Password" required="required">
                                <label for="inputPassword">Password</label>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-label-group">
                                <input type="password" id="confirmPassword" class="form-control" placeholder="Confirm password" required="required">
                                <label for="confirmPassword">Confirm password</label>
                            </div>
                        </div>
                    </div>
                </div>
                <button class="btn btn-primary btn-block" id="btn_register">Register</button>
            </form>
            @if (!User.Identity.IsAuthenticated && !User.IsInRole("Admin"))
            {
                <div class="text-center">
                    <a class="d-block small mt-3" href="@Url.Action("Index","Login")">Login Page</a>
                    <a class="d-block small" href="forgot-password.html">Forgot Password?</a>
                </div>
            }
            else
            {
                <div class="text-center">
                    <a class="d-block small mt-3" href="@Url.Action("Index","Main")">Dashboard Page</a>
                </div>
            }
        </div>
    </div>
</div>
@section Scripts {
    <script src="~/js/Register.js"></script>
}